### ISSUE TITLE
Software Crashing when Saving

### ISSUE THREAD

**Issue by jamietwilliams** [AstroAguirre/subtractAirglow#1]
For COS spectra of white dwarfs, the software is unable to save the corrected spectrum. For Lyman-alpha, every time the software attempts to correct for this, it crashes. For oxygen airglow, occasionally it is able to correct and save but often it crashes too. When it does save, the correction doesn't seem to properly remove the airglow.

![Oxygen_airglow](https://user-images.githubusercontent.com/116102513/236180493-c7557630-e6f8-4043-8f00-a9448999b621.png)

I've attached an example of the oxygen airglow not being corrected.

**Comment by AstroAguirre** [comment]
For Lyman alpha (and occasionally for the oxygen lines), it sometimes takes several seconds to tens of seconds for the software to generate a fit, I have found this to be common when the initial parameters generate a poor fit. This can result in the GUI appearing to crash, but it is working in the background (this is something I would like to fix in the future). One recommendation I have to check this is to use the manual airglow placement option, this produces a fit relatively quickly and parameters can be adjusted afterwards. Regarding the incorrect oxygen airglow subtraction, I am unsure of what could be causing this at the moment. Please feel free to reach out to me over email if you'd like to discuss in more detail.

**Comment by AstroAguirre** [comment]
An incorrect version of GUI.py was uploaded in the initial release (v0.0.1), which is likely causing the issues you described. A new release has just been posted, please try reinstalling this new release and let me know if the situation has improved.
