### ISSUE TITLE
LP5 LSF has different wavelength bins 

### ISSUE THREAD

**Issue by davidjwilson** [AstroAguirre/subtractAirglow#3]
Working with data from COS LP5 so I added the appropriate LSF file to the install directory. Unfortunately, the LP5 LSF files file have changed the wavelength grid to bins of ... 1210, 1215, 1220..., instead of ... 1209, 1214, 1219... as before. At some point Subtract Airglow looks for the 1214 bin, so it doesn't work with the new file. This can be hacked by changing the 1215 value in the LSF file to 1214, but it would be better if the routine knew to look for the 1215 bin when using LP5 data.

**Comment by AstroAguirre** [comment]
I don't think the LP5 (or LP6) LSFs were available on  MAST when the latest version was released, happy to see those available now. I will include this in the next update to the package, for now your temporary solution of swapping 1215 for 1214 in the LP5 files should give the desired result.

**Comment by AstroAguirre** [comment]
The LP5 LSF file is now included in the latest release, v0.1.0.2
